services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mysql
    environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MAIL_HOST=${MAIL_HOST}
        - MAIL_PORT=${MAIL_PORT}
        - MAIL_USERNAME=${MAIL_USERNAME}
        - MAIL_PASSWORD=${MAIL_PASSWORD}
        - REACT_APP_API_URL=${REACT_APP_API_URL}
        - DEFAULT_USER_PASSWORD=${DEFAULT_USER_PASSWORD}
        - SERVER_IP=${SERVER_IP}
        - SERVER_DOMAIN=${SERVER_DOMAIN}
        - SERVER_ENABLED=${SERVER_ENABLED}
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:3000
    depends_on:
      - backend
  mysql:
    build:
      context: ./database
      dockerfile: Dockerfile
      args:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"